# Usa a imagem oficial do Node.js
FROM node:18-alpine

# Define o diretório de trabalho
WORKDIR /app

# Copia o package.json e instala as dependências
COPY package*.json ./
RUN npm install

# Copia o resto do código do frontend
COPY . .

# Expõe a porta do servidor de desenvolvimento
EXPOSE 3000

# Comando para iniciar
CMD ["npm", "start"]
