version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: gestao-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: gestao-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      # --- IMPORTANTE: PREENCHA ESTES VALORES ---
      # Se o banco de dados está a rodar na sua máquina (fora do Docker), use 'host.docker.internal'
      # Se estiver noutro servidor na rede, use o IP ou hostname desse servidor.
      - DB_HOST=host
      - DB_USER=user
      - DB_PASSWORD=senha
      - DB_NAME=gestao_acessos
      - DB_PORT=3306