# Usa a imagem oficial do Node.js
FROM node:18-alpine

# Define o diretório de trabalho
WORKDIR /app

# Copia o package.json e instala as dependências
COPY package*.json ./
RUN npm install

# Copia o resto do código do backend
COPY . .

# Expõe a porta que o nosso servidor irá usar
EXPOSE 4000

# Comando para iniciar o servidor
CMD [ "npm", "start" ]
